### ISSUE TITLE
Investigate security of our endpoints

### ISSUE THREAD

**Issue by John-Moore-UOA** [UoaWDCC/volunteers#136]
### Description:
Are the API endpoints safe? or can anyone with POSTMAN(etc..) call functions like remove user, add user, etc.

### Acceptance Criteria:
- [ ] Understand API endpoints
- [ ] Find out if you need to protect endpoints
- [ ] Protect the endpoints

**Comment by dinoshroom** [comment]
https://docs.google.com/document/d/1W5isCu1AXKCwWkD0puarYBTYCS6e41kUigpCKy7wJlQ/edit?usp=sharing
